services:
    tas2580.ajaxnotification.main:
        class: tas2580\ajaxnotification\controller\main
        arguments:
            - @path_helper
            - @service_container
            - @user
    tas2580.ajaxnotification.listener:
        class: tas2580\ajaxnotification\event\listener
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
        tags:
            - { name: event.listener }